### ISSUE TITLE
YT übliche Tastatur-Bedienung geht nicht

### ISSUE THREAD

**Issue by Leimking** [Eruyome/rocketview#3]
Hey. Erstmal vielen Dank für die Umsetzung.

Ich vermisse allerdings die Bedienung über Tastaturkürzel (Space = Pause/Play, Arrow up/down = Volume, etc.), wie sie auf YouTube üblich ist. Mit der entsprechenden Funktionalität (wie sie auch auf Twitch funktionierte) wäre ich rundum glücklich.

Dankesehr. :o)

**Comment by Eruyome** [comment]
Müsste eigentlich über Javascript zu implementieren sein, ich werds mir auf jeden Fall mal ansehen.

**Comment by Eruyome** [comment]
Implementiert.
